# Generated by Django 3.2.6 on 2021-08-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='artistWebsite',
        ),
        migrations.AddField(
            model_name='work',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
