# Generated by Django 3.2.6 on 2021-09-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20210818_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
