# Generated by Django 3.2.6 on 2021-08-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_work_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='creators',
            field=models.ManyToManyField(blank=True, null=True, related_name='works', to='places.Artist'),
        ),
    ]
