# Generated by Django 3.2.6 on 2021-08-31 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_work_creators'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='work',
            name='creators',
        ),
        migrations.AddField(
            model_name='work',
            name='artist',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='places.artist'),
        ),
    ]
