# Generated by Django 3.2.6 on 2021-08-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20210831_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.IntegerField(default=2, primary_key='True', serialize=False),
        ),
    ]
