# Generated by Django 3.2.6 on 2021-08-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_work_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='artist',
        ),
        migrations.AddField(
            model_name='work',
            name='artist',
            field=models.ManyToManyField(related_name='works', to='places.Artist'),
        ),
    ]
