# Generated by Django 3.2.6 on 2021-08-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20210831_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='artist',
            field=models.ManyToManyField(blank=True, related_name='works', to='places.Artist'),
        ),
    ]
