# Generated by Django 3.2.6 on 2021-08-31 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_work_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='artist',
            new_name='artists',
        ),
    ]
