# Generated by Django 3.2.7 on 2021-09-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_work_photo'),
        ('places', '0011_rename_artist_work_artists'),
    ]

    operations = [
    ]
