# Generated by Django 3.2.7 on 2021-09-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_merge_20210907_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
