# Generated by Django 3.2.7 on 2021-09-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_work_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
